.base: &base
  forwardAgent: true
  multiplexing: true

18.178.55.178: &dev1
  <<: *base
  stage: "develop"
  user: "ec2-user"
  port: 22
  identityFile: "~/.ssh/dmk-dev.pem"
  deploy_path: "/var/www/auger-open/{{application}}"
  branch: "develop"

54.168.169.24:
  <<: *dev1
